{% set data = load_setup_py_data() %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}

package:
    name: "{{ name|lower }}"
    version: "{{ version }}"

source:
    path: ./

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
    host:
        - python
        - pip
    run:
        - python
        - atlassian-python-api ~= 3.8.0
        - incqueryserver-api-python-client ~= 0.19.0.dev2
        - SPARQLWrapper ~= 1.8.5
        - lxml ~= 4.6.2
        - rdflib ~= 5.0.0

about:
    home: http://openmbee.org
    license: Apache 2.0
    license_file: LICENSE
    summary: OpenMBEE Python Library
    description: TBD
